const pokemonList = [
  { name: "Bisasam", img: "/img/bisasam.png", type: "plant" },
  { name: "Endivie", img: "/img/endivie.png", type: "plant" },
  { name: "Knofensa", img: "/img/knofensa.png", type: "plant" },
  { name: "Kokowei", img: "/img/kokowei.png", type: "plant" },
  { name: "Schiggy", img: "/img/schiggy.png", type: "water" },
  { name: "Krabby", img: "/img/krabby.png", type: "water" },
  { name: "Enton", img: "/img/enton.png", type: "water" },
  { name: "Sterndu", img: "/img/sterndu.png", type: "water" },
  { name: "Glumanda", img: "/img/glumanda.png", type: "fire" },
  { name: "Vulpix", img: "/img/vulpix.png", type: "fire" },
  { name: "Fukano", img: "/img/fukano.png", type: "fire" },
  { name: "Hunduster", img: "/img/hunduster.png", type: "fire" },
  { name: "Pikachu", img: "/img/pikachu.png", type: "electric" },
  { name: "Blitza", img: "/img/blitza.png", type: "electric" },
  { name: "Magnetilo", img: "/img/magnetilo.png", type: "electric" },
  { name: "Voltobal", img: "/img/voltobal.png", type: "electric" },
  { name: "Kleinstein", img: "/img/kleinstein.png", type: "rock" },
  { name: "Kabuto", img: "/img/kabuto.png", type: "rock" },
  { name: "Digda", img: "/img/digda.png", type: "rock" },
  { name: "Onyx", img: "/img/onyx.png", type: "rock" }
];